# Generated by Django 5.1.4 on 2024-12-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_avatar_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
