# Generated by Django 5.1.4 on 2024-12-19 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.developer'),
        ),
        migrations.AlterField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(blank=True, to='games.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(blank=True, to='games.platform'),
        ),
    ]
